config/routes.rb
TxtyourcityRails::Application.routes.draw do
  resources :groups
  resources :group_users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }, :path_names => { :sign_up => ENV['SIGN_UP_PATH'] || 'textizen4eva' }
  devise_scope :user do
    match 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  resources :polls do
    put :end, :on => :member # for polls/3/end?
    put :publish, :on => :member
    put :clear_responses, :on => :member # for polls/3/nuke
    collection do
      post "receive_message"
    end
  end

  resources :responses do
    collection do
      post "receive_message"
    end
  end

  match 'welcome' => 'static_pages#home'
  match 'about' => 'static_pages#about'
  match 'privacy' => 'static_pages#privacy'
  match 'getstarted' => 'static_pages#getstarted'

  root :to => 'application#index' #'polls#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  require 'open-uri'
  attr_accessible :name, :poll_ids, :user_ids, :exchange
  has_and_belongs_to_many :polls
  has_many :group_users
  has_many :users, :through => :group_users

  after_save :update_polls

  def update_polls
    unless poll_ids.nil?
      self.polls do |poll|
        poll.destroy unless poll_ids.include?(poll.id) # first delete all removed groups
      end
    end
  end

  def save_users_by_emails(emails, current_user = nil)
    emails.each do |email|
      unless email.blank? or !Devise.email_regexp.match(email)
        user = User.where(:email => email)
        if user.present?
          users << user
        else
          u = User.invite!({:email => email}, current_user)
          u.update_attributes(:role => "editor")
          self.users << u
        end
      end
    end
  end

  def exchanges
    Rails.cache.fetch("group-#{id}-exchanges") do
      self.get_exchanges
    end
  end

  def get_exchanges
    begin
      json = open("https://api.tropo.com/v1/exchanges", :http_basic_authentication=>[ENV['TROPO_USERNAME'], ENV['TROPO_PASSWORD']]).read
      result = JSON.parse(json).find_all{|item| item["smsEnabled"]==true and item["country"] == "United States" } # no canada for now
      result.sort_by! {|x| x['prefix']}
      result_hash = result.reduce(Hash.new()) do |set, val| # concatenate all cities and combine duplicate area codes
        unless set[val['prefix']].nil? # not added to set yet, no duplicates
          unless set[val['prefix']]['city'].casecmp(val['city']) == 0 # unless the cities are the same already (returns 0 if two strings match, case insensitive
            set[val['prefix']]['city'] << ", #{val['city']}"
          end
        else # not added to set yet, add it
          set[val['prefix']] = val
        end
        set
      end
      result_hash.map do |j,i|
        i['label'] = "#{i['prefix'][1,3]} - #{i['city']}, "
        i['label'] << "#{i['state']}" if !i['state'].blank? # just in case
        # i['label'] << "#{i['country']}"
        i
      end
    rescue StandardError=>e
      result_hash = {'1415' => {label: '415 - San Francisco', prefix: '1415'}}
    ensure
      Rails.cache.write("group-#{id}-exchanges", result_hash)
      return result_hash
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /groups
  # GET /groups.json
  def index
    if current_user.role?(:superadmin) # TODO use a cancan ability here instead
      @groups = Group.all
    else
      @grups = current_user.groups
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @editing = true
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if (emails=params[:user_emails])
        @group.save_users_by_emails(emails, current_user)
      end
      @group.users << current_user
      if @group.save
        format.html { redirect_to edit_group_path(@group), notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if (emails=params[:user_emails])
        @group.save_users_by_emails(emails, current_user)
      end

      if @group.update_attributes(params[:group]) 
        format.html { redirect_to edit_group_path(@group), notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else 
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<script>
  $(function() {
    var count = 0;
    appendEmail();
    $(document).on('focus', '.add-email', function(e){
      if (!$(this).hasClass('email-added')){ // only insert a blank email field once per click
        $(this).addClass('email-added');
        $(this).attr('placeholder', "Type any email"); // update the placeholder text
        appendEmail();
      }
    });
    // show the remove link once an email is entered
    $(document).on('change', 'input.add-email', function(e){
      $(this).parent().find('.remove-email').fadeIn();
    });

    function appendEmail(){
      $('#user-list').append('<li id="emailInput'+(count++)+'"><%= text_field_tag "user_emails[]", params[:email], :class => "input add-email email", :placeholder => "Type any email"%> <button class="close remove-email" style="display:none" type="button" onclick="removeEmail(this)">×</button></li>');
    }
  });
  function removeEmail(item){
    $(item).parent().remove();
  }
</script>

<%= simple_form_for @group, :html => { :class => "form-horizontal"} do |f| %>
  <%= f.error_notification %>

<h3>People</h3>
<div>
  <p>Adding some rockstars to this party will give them the same access &mdash; to create and edit polls and view results &mdash; as you. (To share results only, go to the survey page. From there, you can export to CSV or print the webpage to PDF.)</p>
</div>
<br>
  <div id="emails">
    <ol id="user-list">
      <% unless @editing %>
        <li>
        <%= text_field_tag "user_emails[]", params[:email], :placeholder => current_user.email, :disabled => true %><span class="help-inline">You’re automatically a member of any group you create</span>
        </li>
      <% end %>
      <% @group.users.each do |user| %>
        <li>
        <%= user.email %>
        &nbsp;
        <%= link_to "Remove", group_user_path(GroupUser.where(user_id:user, group_id: @group)[0]), :method => :delete, :confirm => "Are you sure?" %> 
        &nbsp;
        <%= link_to "Resend invitation", invitation_resend_path(user.id), :method => :post, :remote => true unless !user.invited_to_sign_up? or user.invitation_accepted? %>

        </li>
      <% end %>
    </ol>

    <%- if @group.errors.messages && @group.errors.messages[:users] -%>
      <ul>
        <div class="control-group error">
          <%- @group.errors.messages[:users].each do |message| -%>
            <li class="help-block"><%= message[0] -%></li>
          <%- end -%>
        </div>
      </ul>
    <%- end -%>
  </div>
  <br>

<% unless @group.new_record? %>
<hr>
  <h3>Polls</h3>
  <div class="row">
    <div class="span6 groupsunit">
      <% if @group.polls.empty? %>
        <div class="caption nopolls">No polls in this group yet.</div>
      <% end %>
      

      <ol class="pollsol">
        <% @group.polls.each do |poll| %>
          <li>
          <span class="pollsol-text"><%= link_to(poll.questions.first.text, poll_path(poll)) %> </span>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
  <br>
<% end %>

<hr>

<h3>Settings</h3>
  <div class="form-inputs">
    <%= f.input :name, :label => "Group name", :hint => "E.g. 'Philadelphia2035' or 'Chattanooga Regional Planning'" %>
    <%= f.input :exchange, :label => "Preferred area code",
      :collection => @group.exchanges
    %>
  <!--
  <%= f.input :name, :label => "Timezone",
    :collection=>[
      ['Eastern Time','EST'],
      ['Central Time','CST'],
      ['Mountain Time','MST'],
      ['Pacific Time','PST'],
      ['Alaska Time','AKST'],
      ['Hawaii Time','HST']
      ], :selected => "EST", :hint => "Used to timestamp responses" %>
  -->
</div>

<br>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-large btn-primary' %>
    <%= link_to 'Cancel', groups_path, :class => 'btn btn-large' %>
    <div class="link-destroy-group">
      <%= link_to(raw('<i class="icon-trash"></i>Destroy'), @group, :class => 'link-danger', confirm: 'This is probably a bad idea. Are you sure?', method: :delete) %>
    </div>
  </div>
<% end %>

app/views/groups/_poll_fields.html.erb
<%= f.input :object_id %>

app/views/groups/_user_fields.html.erb
<div class="nested-fields">
  <%= f.input :email, :label => 'User email' %>
</div>

app/views/groups/edit.html.erb
<div class="row">
  <div class="span12 main">
	<div class="grouptitle">
		Groups › <%= @group.name %>
	</div>

	<%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="span12 main">
  <div class="grouptitle">All Groups</div>

    <table class="table pollslist">
      <% @groups.each do |group| %>
        <tr onClick="window.location.href='<%= edit_group_path(group) %>'">
          <td class="groupname"><%= group.name %></td>

          <td>
            <div class="dashboardresponsecount">
              <%= group.users.count %>
            </div>
            <div class="caption">people</div>
          </td>

          <td>
            <div class="dashboardresponsecount">
              <%= group.polls.count %>
              
            </div>
            <div class="caption">polls</div>
          </td>
          
          <td>
            <%= link_to(raw('<i class="icon-user"></i>Show'), edit_group_path(group)) %>
          </td>

        </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'New Group', new_group_path, :class => "btn btn-large" %>

  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="span12 main">
	<div class="grouptitle">Create a new group</div>

	<%= render 'form' %>
  </div>
</div>

app/views/groups/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
<b>Name:</b>
<%= @group.name %>
</p>

<h3>Polls</h3>
<ul>
  <% @group.polls.each do |poll| %>
    <li>
      <%= link_to poll.questions.first.text, poll_path(poll) %>
    </li>
  <% end %>

</ul>

<h3>Users</h3>
<ul>
  <% @group.users.each do |user| %>
    <li>
    <%= user.email %>  <%= link_to "Remove", group_user_path(GroupUser.where(user_id:user, group_id: @group)[0]), :method => :delete %>
    </li>
  <% end %>

</ul>

<div>Area code: <%= @group.exchange %></div>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>