config/routes.rb
TxtyourcityRails::Application.routes.draw do
  resources :groups
  resources :group_users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :invitations => "invitations" }, :path_names => { :sign_up => ENV['SIGN_UP_PATH'] || 'textizen4eva' }
  devise_scope :user do
    match 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
  end

  resources :polls do
    put :end, :on => :member # for polls/3/end?
    put :publish, :on => :member
    put :clear_responses, :on => :member # for polls/3/nuke
    collection do
      post "receive_message"
    end
  end

  resources :responses do
    collection do
      post "receive_message"
    end
  end

  match 'welcome' => 'static_pages#home'
  match 'about' => 'static_pages#about'
  match 'privacy' => 'static_pages#privacy'
  match 'getstarted' => 'static_pages#getstarted'

  root :to => 'application#index' #'polls#index'

end

app/controllers/invitations_controller.rb
class InvitationsController < Devise::InvitationsController 
  def resend
    User.find(params[:id]).invite! if params[:id]
    
    respond_to do |format|
      format.json { head :no_content }
    end

  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/edit.html.erb
<div class="login-panel">
  <h2><%= t 'devise.invitations.edit.header' %></h2>

  <%= simple_form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put, :class => "form-horizontal" } do |f| %>
    <%= devise_error_messages! %>
    <%= f.hidden_field :invitation_token %>

    <fieldset>
      <div class="control-group">
        <%= f.label :password, "New password", :class => "control-label" %>
        <div class="controls"><%= f.password_field :password %></div>
      </div>
    </fieldset>

    <%= f.input :password_confirmation %>


    <div class="form-actions login-actions">
      <%= f.submit t("devise.invitations.edit.submit_button"), :class => 'btn btn-large btn-primary' %>
      <br>
    </div>

  <% end %>
</div>

app/views/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <%= f.input field %>
<% end -%>

<%= f.submit t("devise.invitations.new.submit_button") %>
<% end %>